[[constraint]]
  name = "cloud.google.com/go"
  version = "^0.30.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/hashicorp/errwrap"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "^1.2.0"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "google.golang.org/api"
  branch = "master"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.14.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
